# Generated by Django 3.2.8 on 2021-11-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20211123_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='avatar_url',
        ),
    ]
